project: 
  type: website
  resources:
    - "*/exampleData/*csv"
    - "*/exampleData/*tsv"
    - "*/exampleData/*txt"
    - "*/exampleData/*xlsx"
    - "*/media/*mp4"
    - "*/media/*png"
    - "*/media/*jpg"
  render:
    - "*.qmd"
    - "*.rmd"
    - "r/*.qmd"
    - "unix/.Rmd"
website:
  title: "Programming classes"
  navbar:
    background: primary
    left:
      - useful_unix.qmd
    right:
      - href: https://karengoncalves.github.io/Karen/
        text: Karen Goncalves
format:
  html:
    theme: darkly