project: 
  type: website
  resources:
    - "*/exampleData/*csv"
    - "*/exampleData/*tsv"
    - "*/exampleData/*txt"
    - "*/exampleData/*xlsx"
    - "*/exampleData/*fasta"
    - "*/media/*mp4"
    - "*/media/*png"
    - "*/media/*jpg"
  render:
    - "*.qmd"
    - "r/*.qmd"
    - "unix/.Rmd"
    - "unix/.qmd"
website:
  title: "Programming classes"
  back-to-top-navigation: true
  reader-mode: true
  page-footer: "Copyright 2023, Ph.D. Karen Cristine Goncalves" 
  navbar:
    background: primary
    left:
      - useful_unix.qmd
      - useful_R.qmd
    right:
      - href: https://karengoncalves.github.io/Karen/
        text: Karen Goncalves
format:
  html:
    theme:
      - darkly
      - custom.scss