---
title: "<span style='display:none'>Programming classes</span>"
author: "<span style='display:none'>Karen Cristine Goncalves, PhD.</span>"
---

<style>

p, ol {
font-size: 1.3em;
line-height: 1.75em
}
</style>

# Classes {.tabset .tabset-pill .tabset-fade}

## Unix/Bash/Terminal

1. [Class 1 - Basics](./unix/Class1_BasicCommands.html)
1. [Class 2 - Connecting to the server and tranfering files](./unix/Class2_Connection_FileTransfer.html)
1. [Class 3 - Running jobs ](./unix/Class3_runningJobs.html)
1. [Class 4 - Running blast ](./unix/Class4_blast.html)
	- Scripts for the class:
	  - [myTry.sh](./unix/scripts_for_class/myTry.sh)
	  - [myGeneralBlast.sh](./unix/scripts_for_class/myGeneralBlast.sh)
	  - [sbatch_blast.sh](./unix/scripts_for_class/sbatch_blast.sh)
	  - [create_master_blast.sh](./unix/scripts_for_class/create_master_blast.sh)
1. [Class 5 - Filtering tables with AWK ](./unix/Class5_AWK.html)
	- [blastn_result.txt](./unix/blastn_result)
	- [prots.fasta](./unix/prots.fasta)
1. [Class 6 - SED commands ](./unix/Class6_SED.html)
<br><br><br><br><br>

## R 

0. [Check this before the first class](./r/Before_1stClass.html)
	- [Example data for class 1](https://karengoncalves.github.io/Programming_classes/r/exampleData/Class1_exampleData.txt)
1. [Class 1 - basics](./r/basics.html)

## Statistics

Coming soon
